/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarIndexRouteImport } from './routes/car.index'
import { Route as CarNovoRouteImport } from './routes/car.novo'
import { Route as CarChecklistRouteImport } from './routes/car.checklist'
import { Route as CarIdRouteImport } from './routes/car.$id'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarIndexRoute = CarIndexRouteImport.update({
  id: '/car/',
  path: '/car/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarNovoRoute = CarNovoRouteImport.update({
  id: '/car/novo',
  path: '/car/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarChecklistRoute = CarChecklistRouteImport.update({
  id: '/car/checklist',
  path: '/car/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CarIdRoute = CarIdRouteImport.update({
  id: '/car/$id',
  path: '/car/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/car/$id': typeof CarIdRoute
  '/car/checklist': typeof CarChecklistRoute
  '/car/novo': typeof CarNovoRoute
  '/car/': typeof CarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/car/$id': typeof CarIdRoute
  '/car/checklist': typeof CarChecklistRoute
  '/car/novo': typeof CarNovoRoute
  '/car': typeof CarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/car/$id': typeof CarIdRoute
  '/car/checklist': typeof CarChecklistRoute
  '/car/novo': typeof CarNovoRoute
  '/car/': typeof CarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/inicio'
    | '/login'
    | '/perfil'
    | '/car/$id'
    | '/car/checklist'
    | '/car/novo'
    | '/car/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/inicio'
    | '/login'
    | '/perfil'
    | '/car/$id'
    | '/car/checklist'
    | '/car/novo'
    | '/car'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/inicio'
    | '/login'
    | '/perfil'
    | '/car/$id'
    | '/car/checklist'
    | '/car/novo'
    | '/car/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  InicioRoute: typeof InicioRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  CarIdRoute: typeof CarIdRoute
  CarChecklistRoute: typeof CarChecklistRoute
  CarNovoRoute: typeof CarNovoRoute
  CarIndexRoute: typeof CarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/': {
      id: '/car/'
      path: '/car'
      fullPath: '/car/'
      preLoaderRoute: typeof CarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/novo': {
      id: '/car/novo'
      path: '/car/novo'
      fullPath: '/car/novo'
      preLoaderRoute: typeof CarNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/checklist': {
      id: '/car/checklist'
      path: '/car/checklist'
      fullPath: '/car/checklist'
      preLoaderRoute: typeof CarChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/$id': {
      id: '/car/$id'
      path: '/car/$id'
      fullPath: '/car/$id'
      preLoaderRoute: typeof CarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  InicioRoute: InicioRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  CarIdRoute: CarIdRoute,
  CarChecklistRoute: CarChecklistRoute,
  CarNovoRoute: CarNovoRoute,
  CarIndexRoute: CarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
